export const GET_PRODUCE = {
    REQUEST: `GET_PRODUCE`,
    SUCCESS: `GET_PRODUCE_SUCCESS`,
    ERROR: `GET_PRODUCE_ERROR`
};

export const POST_PRODUCE = {
    REQUEST: `POST_PRODUCE`,
    SUCCESS: `POST_PRODUCE_SUCCESS`,
    ERROR: `POST_PRODUCE_ERROR`
};