export const GET_WATERINGS = {
    REQUEST: `GET_WATERINGS`,
    SUCCESS: `GET_WATERINGS_SUCCESS`,
    ERROR: `GET_WATERINGS_ERROR`
};

export const POST_WATERING = {
    REQUEST: `POST_WATERING`,
    SUCCESS: `POST_WATERING_SUCCESS`,
    ERROR: `POST_WATERING_ERROR`
};