export const GET_PLANTS = {
    REQUEST: `GET_PLANTS`,
    SUCCESS: `GET_PLANTS_SUCCESS`,
    ERROR: `GET_PLANTS_ERROR`
};

export const POST_PLANT = {
    REQUEST: `POST_PLANT`,
    SUCCESS: `POST_PLANT_SUCCESS`,
    ERROR: `POST_PLANT_ERROR`
};

export const DELETE_PLANT = {
    REQUEST: `DELETE_PLANT`,
    SUCCESS: `DELETE_PLANT_SUCCESS`,
    ERROR: `DELETE_PLANT_ERROR`
};

export const EDIT_PLANT = {
    REQUEST: `EDIT_PLANT`,
    SUCCESS: `EDIT_PLANT_SUCCESS`,
    ERROR: `EDIT_PLANT_ERROR`
};