export const GET_PLANTS = {
    REQUEST: `GET_PLANTS`,
    SUCCESS: `GET_PLANTS_SUCCESS`,
    ERROR: `GET_PLANTS_ERROR`
};

export const POST_PLANT = {
    REQUEST: `POST_PLANT`,
    SUCCESS: `POST_PLANT_SUCCESS`,
    ERROR: `POST_PLANT_ERROR`
};